---
- name: add elastic gpg key
  become: yes
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"

- name: add beats repository
  become: yes
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    state: present

- name: install filebeat
  become: yes
  apt:
    name: filebeat
    state: present

- name: Configure Beats configuration file
  template:
   src: filebeat.yml.j2
   dest: /etc/filebeat/filebeat.yml
   mode: 0644

- name: restart filebeat
  become: yes
  service:
    name: filebeat
    state: restarted