---
#
# Installing logstash
#
# Add Logstash APT repository
- name: Adding logstash APT repository
  apt_repository:
   repo: deb https://artifacts.elastic.co/p... stable main
   state: present
# Installing Logstash
- name: Update repositories cache and install Logstash
  apt:
   name: logstash

# Configure Beats input configuration 02-beats-input.conf
- name: Configure Beats configuration file
  template:
   src: logstash.conf.j2
   dest: /etc/logstash/conf.d/logstash.conf
   mode: 0644

# Start Logstash service
- name: Start Logstash service
  systemd:
   name: logstash
   state: started
   daemon_reload: yes
# Enable Logstash service
- name: Enable Logstash service
  systemd:
   name: logstash
   enabled: yes