---
#
# Installing Kibana
#

- name: Add Elasticsearch apt-key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: presen

# Add the Elasticsearch APT-repository
- name: Adding Elasticsearch APT repository
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
   state: present

# Install Kibana
- name: Update repositories cache and install Kibana
  apt:
   name: kibana
# Update kibana config file to only accept local connections
- name: Updating the config file to restrict outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: 0.0.0.0'
# Enable Kibana service
- name: Enabling Kibana service
  systemd:
   name: kibana
   enabled: yes
   daemon_reload: yes
# Start Kibana service
- name: Starting Kibana service
  systemd:
   name: kibana
   state: started